[global]
# Global Streamlit configuration

# Set to false to disable usage stats
gatherUsageStats = false

[server]
# Server configuration
headless = false
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
# Browser configuration
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
# Theme configuration
primaryColor = "#FF6B35"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
# Runner configuration
magicEnabled = true
installTracer = false
fixMatplotlib = true

[logger]
# Logging configuration
level = "info"
messageFormat = "%(asctime)s %(message)s"

